#
###################################
# Site wide configuration
####################################
#
name: Nette tutors
title: Nette Tutors | Monday Factory
email:
description: Nette tutorials blog-like website
url: https://monday-factory.github.io/nette-tutors
owner:
  name: Monday Factory
  homepage: https://mondayfactory.com
  google:
    analytics:

authors:
  paveljanda:
    name: Pavel Janda

#
###################################
# Jekyll configuration
####################################
#
timezone:          Europe/Prague
markdown:          kramdown
highlighter:       rouge
excerpt_separator: <!--more-->
permalink:         /articles/:year-:month/:title

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

#
###################################
# Site Owner configuration
####################################
#
